name = "WaveSpectra"
uuid = "9da5bd80-4f3d-48a2-a37e-447dff2ef7bc"
authors = ["Sandia National Laboratories"]
version = "0.1.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
DimensionfulAngles = "2d4b8d7a-02d9-40f9-9abe-9c695b77de0d"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulEquivalences = "da9c4bc3-91c8-4f02-8a40-6b990d2a7e0c"

[compat]
AxisArrays = "0.4"
DimensionfulAngles = "0.2"
Integrals = "4"
Plots = "1"
Unitful = "1"
UnitfulEquivalences = "0.2"
